pluginManagement {
    includeBuild("submodule/generate-graphql-schema-document-gradle-plugin")
}

rootProject.name = 'EduOne'

include 'eduone-web'
include 'eduone-domain-api'
include 'eduone-common'
include 'eduone-business-common'
include 'eduone-query-common'
include 'eduone-repository'
include 'eduone-query-kernel'
include 'eduone-business-kernel'
include 'eduone-query-gateway'
include 'eduone-business-gateway'
include 'eduone-query-contract'
include 'eduone-query-contract-adapter'
include ':submodule:library-kaptcha'