[versions]
springBoot = "4.0.6"
springDependencyManagement = "1.1.7"
mysqlConnectorJ = "9.7.0"
mybatisPlusBom = "3.5.16"
apacheCommonsCollections4 = "4.5.0"
apacheCommonsLang3 = "3.20.0"
graphqlJavaExtendedScalars = "24.0"

[libraries]
lombok = { module = "org.projectlombok:lombok" }
slf4j-api = { module = "org.slf4j:slf4j-api" }
org-springframework-spring-context = { module = "org.springframework:spring-context" }
org-springframework-boot-spring-boot = { module = "org.springframework.boot:spring-boot" }
org-springframework-boot-spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
org-springframework-boot-spring-boot-starter-data-redis = { module = "org.springframework.boot:spring-boot-starter-data-redis" }
org-springframework-boot-spring-boot-starter-graphql = { module = "org.springframework.boot:spring-boot-starter-graphql" }
org-springframework-boot-spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
org-springframework-boot-spring-boot-jackson = { module = "org.springframework.boot:spring-boot-jackson" }
org-springframework-boot-spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
com-mysql-mysql-connector-j = { module = "com.mysql:mysql-connector-j", version.ref = "mysqlConnectorJ" }
mybatis-plus-bom = { module = "com.baomidou:mybatis-plus-bom", version.ref = "mybatisPlusBom" }
com-baomidou-mybatis-plus-jsqlparser = { module = "com.baomidou:mybatis-plus-jsqlparser" }
com-baomidou-mybatis-plus-spring-boot4-starter = { module = "com.baomidou:mybatis-plus-spring-boot4-starter" }
org-apache-commons-commons-collections4 = { module = "org.apache.commons:commons-collections4", version.ref = "apacheCommonsCollections4" }
org-apache-commons-commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "apacheCommonsLang3" }
graphql-java-extended-scalars = { module = "com.graphql-java:graphql-java-extended-scalars", version.ref = "graphqlJavaExtendedScalars" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
