plugins {
    alias libs.plugins.spring.boot
    id("io.github.summerain0.generate-graphql-schema-document-gradle-plugin")
}

description = "Web应用启动模块"

dependencies {
    api(project(":eduone-repository"))
    api(project(":eduone-business-gateway"))
    api(project(":eduone-query-gateway"))
    api(project(":eduone-query-contract-adapter"))
    api(libs.com.mysql.mysql.connector.j)
    api(libs.graphql.java.extended.scalars)
}