type Query
type Mutation
directive @page(for: String!) on FIELD_DEFINITION
directive @commonBusinessResponse(for: String!) on FIELD_DEFINITION
scalar DateTime
scalar Int
scalar Long
scalar String

"""业务字典信息响应体"""
type BusinessDictionaryResponse {
    """字典ID"""
    id: String
    """字典类型"""
    type: String
    """字典编码"""
    code: String
    """字典名称"""
    name: String
    """上级字典ID"""
    parentId: String
    """字典状态"""
    status: String
    """排序"""
    sort: Int
    """更新人用户ID"""
    updateUserId: String
    """更新时间"""
    updateTime: DateTime
    """创建人用户ID"""
    createUserId: String
    """创建时间"""
    createTime: DateTime
}

"""业务字典类型信息响应体"""
type BusinessDictionaryTypeResponse {
    """字典类型"""
    type: String
    """字典类型名称"""
    name: String
    """字典类型描述"""
    desc: String
    """更新人用户ID"""
    updateUserId: String
    """更新时间"""
    updateTime: DateTime
    """创建人用户ID"""
    createUserId: String
    """创建时间"""
    createTime: DateTime
}

"""图形验证码响应内容"""
type ImageCaptchaResponse {
    """经过base64编码后的验证码图片"""
    imageBase64: String
    """业务Token"""
    token: String
}

"""地区树查询响应"""
type RegionTreeResponse {
    """地区ID"""
    id: String
    """地区编码"""
    code: String
    """上级地区ID"""
    parentId: String
    """上级地区编码"""
    parentCode: String
    """地区路径"""
    path: String
    """地区层级"""
    level: Int
    """地区名称"""
    name: String
    """地区排序"""
    sort: Int
    """地区状态"""
    status: String
}

"""用户登录成功响应体"""
type UserLoginSuccessResponse {
    """用户ID"""
    userId: String
    """访问令牌"""
    accessToken: String
    """刷新令牌"""
    refreshToken: String
}

"""获取验证码请求体"""
input ApplyImageCaptchaRequest {
    """验证场景"""
    verificationScene: String
    """验证上下文token"""
    token: String
}

"""业务字典查询条件请求体"""
input BusinessDictionaryRequest {
    """字典ID集合"""
    idList: [String]
    """字典类型"""
    type: String
    """上级字典ID"""
    parentId: String
    """字典编码集合"""
    codeList: [String]
}

"""业务字典排序条件请求体"""
input BusinessDictionarySortRequest {
    """排序字段"""
    field: BusinessDictionarySortField
    """排序方向"""
    direction: OrderDirection
}

"""业务字典类型查询条件请求体"""
input BusinessDictionaryTypeRequest {
    """字典类型名称"""
    name: String
}

"""业务字典类型排序条件请求体"""
input BusinessDictionaryTypeSortRequest {
    """排序字段"""
    field: BusinessDictionaryTypeSortField
    """排序方向"""
    direction: OrderDirection
}

"""验证图形验证码请求体"""
input ImageCaptchaValidRequest {
    """验证场景"""
    verificationScene: String
    """校验上下文token"""
    token: String
    """验证码"""
    code: String
}

input LoginWithPasswordRequest {
    account: String
    password: String
    token: String
}

"""分页请求条件"""
input PageRequest {
    """当前页码"""
    pageNo: Long
    """每页数量"""
    pageSize: Long
}

"""地区树查询条件"""
input RegionTreeQueryRequest {
    """上级地区ID，-1表示顶级"""
    parentIdList: [String]
    """上级地区编码，-1表示顶级"""
    parentCodeList: [String]
    """地区ID，-1表示顶级"""
    idList: [String]
    """地区编码，-1表示顶级"""
    codeList: [String]
    """地区状态"""
    status: String
}

"""业务字典排序字段枚举"""
enum BusinessDictionarySortField {
    """排序"""
    SORT
    """创建时间"""
    CREATE_TIME
}

"""业务字典类型排序字段枚举"""
enum BusinessDictionaryTypeSortField {
    """创建时间"""
    CREATE_TIME
}

"""排序方向枚举"""
enum OrderDirection {
    """升序"""
    ASC
    """降序"""
    DESC
}